server: 
  port: 8082
app:
    checkAVLCronJob: 0 0/20 * * * ?
    checkByDistrictURL: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id={districtId}&date={dateVal}
    checkByPincodeURL: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode={pinCode}&date={dateVal}
    dateFormat: dd-MM-yyyy
    debugTelegramChatId: 
    emailAuth: true
    emailFrom: 
    emailFromPassword: 
    emailHost: smtp.gmail.com
    emailSmtpPort: 587
    emailSocketFactory: 465
    emailSocketFactoryClass: javax.net.ssl.SSLSocketFactory
    host: 
    appHost: 
    logChatbotCron: 0 0/15 * * * ?
    maxNotificationPerAlertPerDay: 12
    appPort: 80
    telegramBotName: 
    telegramBotToken: 
    timeDifferenceBetweenPreviousNotificationInMins: 42
    twiloAccoundSid: 
    twiloAuthToken: 
    twiloSendNumber: 
logging:
    level:
        com:
            prateek:
                cowinAvailibility: DEBUG
        org:
            hibernate: ERROR
        root: INFO